# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iyjkAmZVZmxfaHL05OMvsqBkixySnXUk
"""

numero = int(input('digite o numero: '))
if numero % 2 == 0:
    print(f'0 {numero} é par')
else:
    print(f'o numero {numero} é impar')

a = 0
while a<5:
    print('pegue agua')
    print('fotografo')
    a=a+1
print('fim')

nome = 'sara'
for s in  nome:
    print(s)

lista = ['ana', 'pedro', 'sofia', 'antonio', 'samara','victor', 'rafael', 'manoel']
lista.sort()
for pessoa in lista:
    print(pessoa)

for c in range (1,10,2):
    print(c)

